4 task. Histogram
js-tasks-ru/htmlcss-20231222_gladysheva-pv pull request #5
Opened 2024-01-19 12:35 UTC by gladysheva-pv

2024-01-19 12:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-19 13:16 UTC, GSemikozov requested changes

2024-01-19 13:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    border-color: var(--grey-3);
такие штуки лучше в общем свойстве `border` описывать

2024-01-19 13:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    font-family: 'Inter';
не хватает паддингов

2024-01-19 13:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 16px 0px 6px 24px;
см выше - лучше задать на уровне родителя 1 раз, чем на уровне каждого из дочерних элементов)

2024-01-19 13:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    display: inline-block;
лишнее

2024-01-19 13:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    text-align: right;
лишнее

2024-01-19 13:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    float: right;
про флоаты если вдруг что-то и известно - то лучше сразу забыть)) у нас как минимум есть флексы

2024-01-19 13:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 19px 24px;
см выше

2024-01-19 13:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-left: 24px;
см выше

2024-01-19 13:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding-bottom: 39px;
а это - марджин (отталкиваемся от соседей, а не смещаем что-то внутри)

2024-01-19 13:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    flex-flow: row;
лишнее

2024-01-19 13:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    justify-content: space-evenly;
лишнее

2024-01-19 13:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    padding: 0px 26px 24px 26px;
лишнее

2024-01-19 13:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +}
а вот чего не хватает - height: 50px + gap: 1px

2024-01-19 13:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    align-self: flex-end;
поскольку поведение общее для всех элементов - то лучше align-items: flex-end на уровне .histogram__data

2024-01-19 13:16 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    margin-left: 1px
если gap на уровне родителя поставим - марджин не нужен

2024-01-19 13:16 UTC, GSemikozov commented on 04-lection2/01-histogram/index.html
> +            <div class="histogram__header">Total orders</div>
хедер лучше как-то сгруппировать - чтобы ссылка и заголовок были на одном уровне, а значение /цифры - ниже

2024-01-19 17:04 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-21 14:56 UTC, GSemikozov requested changes

2024-01-21 14:56 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +.histogram__headeritem_link {
это самостоятельный элемент - .histogram__link

2024-01-21 14:56 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    text-align: right;
лишнее

2024-01-21 14:56 UTC, GSemikozov commented on 04-lection2/01-histogram/histogram.css
> +    /*padding-top: 3px;*/
а вот это как раз надо, только - марджин

2024-01-21 21:58 UTC, GSemikozov approved these changes

2024-01-21 21:58 UTC, merged