4 task. skeleton
js-tasks-ru/htmlcss-20231222_gladysheva-pv pull request #6
Opened 2024-01-20 20:36 UTC by gladysheva-pv

2024-01-20 20:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-21 14:58 UTC, GSemikozov requested changes

2024-01-21 14:58 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +            <svg class="skeleton__item_circle" width="64" height="64" viewBox="0 0 64 64" fill="none" xmlns="http://www.w3.org/2000/svg">
skeleton__circle

2024-01-21 14:58 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding: 24px;
немного неточно)

2024-01-21 14:58 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    width: 579px;
лишнее

2024-01-21 14:58 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    flex-wrap: wrap;
можно просто flex-direction: column

2024-01-21 14:58 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    margin-bottom: 8px;
всегда ли снизу нужен этот марджин?

2024-01-21 14:58 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__item {
у нас 4 использования данного айтема, и во всех случаях - разная ширина. Точно ли все как на макете? Если нет, то управляем шириной за счет модификаторов

2024-01-21 14:58 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    flex-shrink: 0;
может свг, а может и пнг - поэтому размеры задаем в этом классе

2024-01-21 20:05 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-21 20:15 UTC, gladysheva-pv commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__item {
На макете ширина как у меня - следовательно, 172, 257, 515 и 515

2024-01-21 20:18 UTC, gladysheva-pv commented on 04-lection2/02-skeleton/skeleton.css
> +    flex-wrap: wrap;
Нельзя, тогда горизонтальные линии не встанут одновременно рядом с кругом и под кругом

2024-01-21 20:26 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-01-21 21:59 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__item {
размеры блока могут меняться, они не статичны, следовательно - ширину нужно задать в процентах

2024-01-21 21:59 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    flex-wrap: wrap;
поэтому их правильнее было бы объединить в другом элементе, который бы и размещался на одном уровне с кругом)

2024-01-21 22:01 UTC, GSemikozov requested changes

2024-01-21 22:01 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    padding: 24px;
`24px 40px 32px 24px`

2024-01-21 22:01 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +    flex-wrap: wrap;
ну и задавать надо не инлайном, а через модификаторы (в отличие от гистограммы где 100 вариаций здесь у нас всего максимум 4 варианта)

2024-01-22 11:17 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-22 15:35 UTC, GSemikozov requested changes

2024-01-22 15:35 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +            <div class="wrapper_icon">
это модификатор или элемент?
вне зависимости от ответа класс оформлен неправильно - блок называется skeleton, а всешго его элементы - начинаются с префикса `skeleton__`

2024-01-22 15:35 UTC, GSemikozov commented on 04-lection2/02-skeleton/index.html
> +                <div class="wrapper_icon_text">
и тут

2024-01-22 16:34 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-25 20:58 UTC, GSemikozov requested changes

2024-01-25 20:58 UTC, GSemikozov commented on 04-lection2/02-skeleton/skeleton.css
> +.skeleton__wrapper_text {
по способу именования класса оч похоже на модификатор. Но - это ведь элемент, не модификатор, верно?) тогда все-таки правильнее .skeleton__wrapper-text

2024-01-26 13:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-01-27 14:12 UTC, GSemikozov approved these changes

2024-01-27 14:12 UTC, merged