5 task. calendar
js-tasks-ru/htmlcss-20231222_gladysheva-pv pull request #8
Opened 2024-02-02 12:21 UTC by gladysheva-pv

2024-02-02 12:21 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-02 14:55 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-02-02 15:17 UTC, GSemikozov requested changes

2024-02-02 15:17 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    padding: 28px 36px;
все-таки `28 26 32`)

2024-02-02 16:25 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-03 07:25 UTC, GSemikozov approved these changes

2024-02-03 07:25 UTC, merged