5 task modal
js-tasks-ru/htmlcss-20231222_gladysheva-pv pull request #9
Opened 2024-02-02 16:36 UTC by gladysheva-pv

2024-02-02 16:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-02-02 16:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2024-02-03 07:28 UTC, GSemikozov requested changes

2024-02-03 07:28 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    padding: 28px;
паддинги, max-width + background + border-radius - уносим в элемент .modal__window, а сам блок - должен растягиваться на весь вьюпорт

2024-02-03 07:28 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    left: 50%;
по середине будет именно .modal__window (можно как через absolute, так и через родителя)

2024-02-03 07:28 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    left: 100%;
лучше top + right в пикселях

2024-02-03 07:28 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__overlay {
этот элемент не нужен, фон через rgba можно задать сразу на блок

2024-02-09 12:57 UTC, GSemikozov requested changes

2024-02-09 12:57 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal_window {
.modal__window

2024-02-09 12:57 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__close :hover {
пробел лишний)

2024-02-25 06:22 UTC, GSemikozov approved these changes

2024-02-25 06:22 UTC, merged